package fix

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/stxkxs/matlock/internal/cloud"
)

// Options controls fix file generation.
type Options struct {
	OutputDir string
	Severity  cloud.Severity
}

// GenerateTerraform writes one .tf file per principal with minimal policy resources.
func GenerateTerraform(findings []cloud.Finding, policies map[string]cloud.Policy, opts Options) error {
	if err := os.MkdirAll(opts.OutputDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	type entry struct {
		principal cloud.Principal
		policy    cloud.Policy
	}
	seen := make(map[string]entry)
	for _, f := range findings {
		if f.Principal == nil {
			continue
		}
		if cloud.SeverityRank(f.Severity) < cloud.SeverityRank(opts.Severity) {
			continue
		}
		pid := f.Principal.ID
		if _, ok := seen[pid]; !ok {
			seen[pid] = entry{principal: *f.Principal, policy: policies[pid]}
		}
	}

	for _, e := range seen {
		if err := writePrincipalTF(e.principal, e.policy, opts.OutputDir); err != nil {
			return err
		}
	}
	return nil
}

func writePrincipalTF(principal cloud.Principal, policy cloud.Policy, dir string) error {
	s := slug(principal.Name)
	filename := filepath.Join(dir, "minimal_"+s+".tf")

	var content string
	switch principal.Provider {
	case "aws":
		content = formatAWSTF(s, principal.Name, policy)
	case "gcp":
		content = formatGCPTF(s, principal.Name, policy)
	case "azure":
		if err := writeAzureJSON(s, policy, dir); err != nil {
			return err
		}
		content = fmt.Sprintf("# Azure custom role JSON written to %s_role.json\n", s)
	default:
		content = fmt.Sprintf("# no Terraform template available for provider %q\n", principal.Provider)
	}

	return os.WriteFile(filename, []byte(content), 0o644)
}

func formatAWSTF(s, name string, policy cloud.Policy) string {
	policyExpr := `jsonencode({})`
	if len(policy.Raw) > 0 {
		policyExpr = "jsonencode(" + string(policy.Raw) + ")"
	}
	return fmt.Sprintf(`resource "aws_iam_policy" "minimal_%s" {
  name        = "minimal-%s"
  description = "Minimal policy generated by matlock"
  policy      = %s
}
`, s, strings.ReplaceAll(name, "_", "-"), policyExpr)
}

func formatGCPTF(s, name string, policy cloud.Policy) string {
	perms := extractGCPPermissions(policy.Raw)
	var sb strings.Builder
	for _, p := range perms {
		fmt.Fprintf(&sb, "    %q,\n", p)
	}
	return fmt.Sprintf(`resource "google_project_iam_custom_role" "minimal_%s" {
  role_id     = "minimal_%s"
  title       = "Minimal role for %s"
  permissions = [
%s  ]
}
`, s, s, name, sb.String())
}

func writeAzureJSON(s string, policy cloud.Policy, dir string) error {
	if len(policy.Raw) > 0 {
		if err := os.WriteFile(filepath.Join(dir, s+"_role.json"), policy.Raw, 0o644); err != nil {
			return fmt.Errorf("write azure role json: %w", err)
		}
	}
	return nil
}

func extractGCPPermissions(raw []byte) []string {
	type role struct {
		Permissions []string `json:"includedPermissions"`
	}
	var r role
	_ = json.Unmarshal(raw, &r)
	return r.Permissions
}

func slug(name string) string {
	return strings.NewReplacer(
		"/", "_", "@", "_at_", ".", "_", "-", "_", " ", "_",
	).Replace(strings.ToLower(name))
}
