package gcp

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"google.golang.org/api/cloudresourcemanager/v1"
	googleiam "google.golang.org/api/iam/v1"

	"github.com/stxkxs/matlock/internal/cloud"
)

// crmAPI is the narrow Cloud Resource Manager surface used by this package.
// Production: wraps *cloudresourcemanager.Service via crmAdapter.
type crmAPI interface {
	GetIAMPolicy(ctx context.Context, projectID string) (*cloudresourcemanager.Policy, error)
}

// googleIAMAPI is the narrow GCP IAM surface used by this package.
// Production: wraps *iam.Service via googleIAMAdapter.
type googleIAMAPI interface {
	GetRole(ctx context.Context, roleName string) (*googleiam.Role, error)
}

type crmAdapter struct{ svc *cloudresourcemanager.Service }

func (a *crmAdapter) GetIAMPolicy(ctx context.Context, projectID string) (*cloudresourcemanager.Policy, error) {
	return a.svc.Projects.GetIamPolicy(projectID, &cloudresourcemanager.GetIamPolicyRequest{}).Context(ctx).Do()
}

type googleIAMAdapter struct{ svc *googleiam.Service }

func (a *googleIAMAdapter) GetRole(ctx context.Context, roleName string) (*googleiam.Role, error) {
	role, err := a.svc.Roles.Get(roleName).Context(ctx).Do()
	if err != nil {
		role, err = a.svc.Projects.Roles.Get(roleName).Context(ctx).Do()
		if err != nil {
			return nil, err
		}
	}
	return role, nil
}

// ListPrincipals returns all unique members from the project's IAM policy.
func (p *Provider) ListPrincipals(ctx context.Context) ([]cloud.Principal, error) {
	policy, err := p.crm.GetIAMPolicy(ctx, p.projectID)
	if err != nil {
		return nil, fmt.Errorf("get IAM policy: %w", err)
	}

	seen := make(map[string]bool)
	var principals []cloud.Principal
	for _, binding := range policy.Bindings {
		for _, member := range binding.Members {
			if seen[member] {
				continue
			}
			seen[member] = true
			pt, name := parseMember(member)
			principals = append(principals, cloud.Principal{
				ID:       member,
				Name:     name,
				Type:     pt,
				Provider: "gcp",
				Metadata: map[string]string{"member": member, "project": p.projectID},
			})
		}
	}
	return principals, nil
}

// parseMember splits "serviceAccount:sa@project.iam.gserviceaccount.com" into type + name.
func parseMember(member string) (cloud.PrincipalType, string) {
	parts := strings.SplitN(member, ":", 2)
	if len(parts) != 2 {
		return cloud.PrincipalUser, member
	}
	kind, name := parts[0], parts[1]
	switch kind {
	case "serviceAccount":
		return cloud.PrincipalServiceAccount, name
	case "user", "group":
		return cloud.PrincipalUser, name
	default:
		return cloud.PrincipalUser, name
	}
}

// GrantedPermissions resolves all role bindings for a member to a flat permission list.
func (p *Provider) GrantedPermissions(ctx context.Context, principal cloud.Principal) ([]cloud.Permission, error) {
	member := principal.Metadata["member"]
	if member == "" {
		member = principal.ID
	}

	policy, err := p.crm.GetIAMPolicy(ctx, p.projectID)
	if err != nil {
		return nil, fmt.Errorf("get IAM policy: %w", err)
	}

	var allPerms []cloud.Permission
	for _, binding := range policy.Bindings {
		for _, m := range binding.Members {
			if m != member {
				continue
			}
			role, err := p.googleIAM.GetRole(ctx, binding.Role)
			if err != nil {
				continue // best-effort
			}
			for _, perm := range role.IncludedPermissions {
				allPerms = append(allPerms, cloud.Permission{
					Action:   perm,
					Resource: "projects/" + p.projectID,
				})
			}
		}
	}
	return allPerms, nil
}

// UsedPermissions queries Cloud Audit Logs for actions taken by the principal.
// Delegated to auditlogs.go.
func (p *Provider) UsedPermissions(ctx context.Context, principal cloud.Principal, since time.Time) ([]cloud.Permission, error) {
	return p.auditLogPermissions(ctx, principal, since)
}

// MinimalPolicy builds a GCP custom role definition from used permissions.
func (p *Provider) MinimalPolicy(_ context.Context, principal cloud.Principal, used []cloud.Permission) (cloud.Policy, error) {
	seen := make(map[string]bool)
	var perms []string
	for _, u := range used {
		if !seen[u.Action] {
			seen[u.Action] = true
			perms = append(perms, u.Action)
		}
	}

	type customRole struct {
		Title       string   `json:"title"`
		Description string   `json:"description"`
		Permissions []string `json:"includedPermissions"`
		Stage       string   `json:"stage"`
	}
	role := customRole{
		Title:       "Minimal role for " + principal.Name,
		Description: "Auto-generated by matlock — contains only observed permissions",
		Permissions: perms,
		Stage:       "GA",
	}
	raw, err := json.MarshalIndent(role, "", "  ")
	if err != nil {
		return cloud.Policy{}, err
	}
	return cloud.Policy{
		Provider: "gcp",
		Format:   "gcp-custom-role",
		Raw:      raw,
	}, nil
}
